steps:
- name: 'gradle:6.2.2-jdk11'
  entrypoint: gradle
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/bowerzoom', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/bowerzoom' ]