steps:
- name: 'gradle:5.6.2-jdk8'
  entrypoint: gradle
  args: ['build']
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/bowerzoom', '.' ]
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/$PROJECT_ID/bowerzoom' ]